### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by FineSam** [DRuggeri/bind_query_exporter#1]
Hello
I saw your exporter and wanted to give it a try.
It looks really usefull since you don't need to restart named for your exporter to work.

My newbie problem is that I can't figure how to install the binaries you provided on my CentOS machine .
All I get is a lot of .XXX files that I don't know what to do with...
![image](https://user-images.githubusercontent.com/25651706/93326138-54637680-f853-11ea-993a-d66ef903991c.png)

Sorry for the beginner question.

**Comment by DRuggeri** [comment]
Hey there, @FineSam. No worries about the question... but I'm actually not sure how you came to this point? I don't recognize any of these files. The binaries in the release page should just be able to be downloaded directly to your machine (usually in `/usr/local/bin`) and executed from there.

For example:

```
wget -O /usr/local/bin/bind_query_exporter https://github.com/DRuggeri/bind_query_exporter/releases/download/v2.1.0/bind_query_exporter-v2.1.0-linux-amd64
chmod 755 /usr/local/bin/bind_query_exporter
```

Once that's done, and you are happy with how the exporter works, you could drop a systemd or init script on the machine to start it with the machine.

I'll keep this issue open in case we have more to discuss about some of these odd files - hope this helps, though!

**Comment by FineSam** [comment]
Hi @DRuggeri, thank you for your answer.
I tried your example using wget and everything went great!
I suppose my error was that I downloaded the package on Windows and then sent it to my Linux machine.

Thank you again!
