### ISSUE TITLE
The collector can read more than one query_ Log file?

### ISSUE THREAD

**Issue by yjlmzh** [DRuggeri/bind_query_exporter#2]
The collector can read more than one query_ Log file?

/var/log/bind/queries.log /var/log/bind2/queries.log /var/log/bind3/queries.log

**Comment by DRuggeri** [comment]
Hi, @yjlmzh. No, I'm afraid not. In the case where multiple BIND daemons are running on the same node, it would be best to run multiple exporters. This shouldn't be too costly because the exporter is very lean.
