### ISSUE TITLE
When cutting logs with logrotate, bind_ query_ exporter stops collecting information

### ISSUE THREAD

**Issue by yjlmzh** [DRuggeri/bind_query_exporter#3]
When cutting logs with logrotate, bind_ query_ exporter stops collecting information. Unable to recover

![image](https://user-images.githubusercontent.com/49852688/96566794-98d1ae80-12f8-11eb-98b2-a75330321760.png)

**Comment by DRuggeri** [comment]
Hi, @yjlmzh - sorry for the slow response. I think this is caused because I had not set the `ReOpen` config setting. I've added this in 7e73c19c28445575e985ba4c1701a93783d43432 and released as `v2.1.1`. Let me know if that helps!

**Comment by DRuggeri** [comment]
I hope that helps resolve the issue for you - closing the issue, but let me know if the fix didn't cover you.
