### ISSUE TITLE
queries.log is empty

### ISSUE THREAD

**Issue by rezshar** [DRuggeri/bind_query_exporter#4]
hello 
in my server the bind service deploy as a docker container and all path is a volume for that.
all logs redirect to /var/log/syslog but when i run exporter the queries.log is empty and nothing to show after.

` ./bind_query_exporter-v2.1.1-linux-amd64 --log="/var/log/bind/queries.log" 
INFO[0000] Starting bind_query_exporter (version=, branch=, revision=)  source="bind_query_exporter.go:163"
INFO[0000] Build context (go=go1.14.6, user=, date=)     source="bind_query_exporter.go:164"
INFO[0000] Listening on :9197                            source="bind_query_exporter.go:233"
`
could you help me ?

**Comment by DRuggeri** [comment]
Hi, @rezshar. I'm afraid I don't know enough about your configuration to be able to offer a suggestion. Are you saying that bind is not emitting a query log as configured? As you can imagine, that's a required first step that has to work for this exporter to be able to consume the logfile.

**Comment by rezshar** [comment]
my problem solved.
i setup docker logs driver for my container, after that docker redirect all logs to syslog, finally insert these configuration in the end of named.conf and restart my container.


`logging {
channel syslog { syslog daemon; severity info; };
channel stdout { stderr; severity info; };
channel transfer_log {
file "/var/log/bind/bind.log";
severity info;
print-category yes;
print-severity yes;
print-time yes;
};
channel query_log {
file "/var/log/bind/queries.log";
severity debug;
print-category yes;
print-severity yes;
print-time yes;
};
category default { syslog; stdout; };
category update { syslog; };
category update-security { syslog; };
category security { syslog; };
category queries { query_log; stdout; };
category xfer-in { transfer_log; stdout; };
category xfer-out { transfer_log; stdout;};
category lame-servers { null; };
};
`thanks @DRuggeri for your response
