### ISSUE TITLE
cannot find package "github.com/hpcloud/tail"

### ISSUE THREAD

**Issue by ghost** [DRuggeri/bind_query_exporter#5]
When trying to execute docker build, the following issue is encountered:

`[root@ns1 bind_query_exporter]# docker build -t bind_query_exporter .
Sending build context to Docker daemon  154.1kB

Step 1/11 : FROM golang:buster as builder
 ---> 3360fba69704

Step 2/11 : RUN mkdir -p /app/src/github.com/DRuggeri/bind_query_exporter
 ---> Using cache
 ---> 63efec2ae5d8

Step 3/11 : ENV GOPATH /app
 ---> Using cache
 ---> 099beeac8168

Step 4/11 : WORKDIR /app
 ---> Using cache
 ---> 1fb7f1630bdb

Step 5/11 : COPY . /app/src/github.com/DRuggeri/bind_query_exporter
 ---> Using cache
 ---> 708e4687df13

Step 6/11 : RUN go install github.com/DRuggeri/bind_query_exporter
 ---> Running in 5f5ef980688c
src/github.com/DRuggeri/bind_query_exporter/bind_query_exporter.go:9:2: cannot find package "github.com/hpcloud/tail" in any of:
        /usr/local/go/src/github.com/hpcloud/tail (from $GOROOT)
        /app/src/github.com/hpcloud/tail (from $GOPATH)
src/github.com/DRuggeri/bind_query_exporter/collectors/names_collector.go:5:2: cannot find package "github.com/prometheus/client_golang/prometheus" in any of:
        /usr/local/go/src/github.com/prometheus/client_golang/prometheus (from $GOROOT)
        /app/src/github.com/prometheus/client_golang/prometheus (from $GOPATH)
src/github.com/DRuggeri/bind_query_exporter/bind_query_exporter.go:11:2: cannot find package "github.com/prometheus/client_golang/prometheus/promhttp" in any of:
        /usr/local/go/src/github.com/prometheus/client_golang/prometheus/promhttp (from $GOROOT)
        /app/src/github.com/prometheus/client_golang/prometheus/promhttp (from $GOPATH)
src/github.com/DRuggeri/bind_query_exporter/collectors/names_collector.go:6:2: cannot find package "github.com/prometheus/common/log" in any of:
        /usr/local/go/src/github.com/prometheus/common/log (from $GOROOT)
        /app/src/github.com/prometheus/common/log (from $GOPATH)
src/github.com/DRuggeri/bind_query_exporter/bind_query_exporter.go:13:2: cannot find package "github.com/prometheus/common/version" in any of:
        /usr/local/go/src/github.com/prometheus/common/version (from $GOROOT)
        /app/src/github.com/prometheus/common/version (from $GOPATH)
src/github.com/DRuggeri/bind_query_exporter/bind_query_exporter.go:14:2: cannot find package "gopkg.in/alecthomas/kingpin.v2" in any of:
        /usr/local/go/src/gopkg.in/alecthomas/kingpin.v2 (from $GOROOT)
        /app/src/gopkg.in/alecthomas/kingpin.v2 (from $GOPATH)
The command '/bin/sh -c go install github.com/DRuggeri/bind_query_exporter' returned a non-zero code: 1
`

**Comment by DRuggeri** [comment]
Hey there, @novafiddler - thanks for the report. This has been fixed (wrong working directory) - feel free to give it another go.
